--  *********************************************************************
--  Update Database Script
--  *********************************************************************
--  Change Log: update.xml
--  Ran at: 5/1/15 1:49 PM
--  Against: root@localhost@jdbc:mysql://localhost/HR
--  Liquibase version: 3.3.2
--  *********************************************************************

--  Lock Database
UPDATE HR.DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = 'VINETTES-TP (192.168.2.38)', LOCKGRANTED = '2015-05-01 13:49:15.920' WHERE ID = 1 AND LOCKED = 0;

--  Create Database Change Log Table
CREATE TABLE HR.DATABASECHANGELOG (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED datetime NOT NULL, ORDEREXECUTED INT NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35) NULL, DESCRIPTION VARCHAR(255) NULL, COMMENTS VARCHAR(255) NULL, TAG VARCHAR(255) NULL, LIQUIBASE VARCHAR(20) NULL);

--  Changeset v000/20150501_1.xml::1::vinettes
CREATE TABLE HR.departments (ID INT AUTO_INCREMENT NOT NULL, NAME CHAR(50) NOT NULL COMMENT 'The department name', TERRITORY_ID INT NOT NULL COMMENT 'The department territory.', CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (ID)) COMMENT='To capture the departments.';

ALTER TABLE HR.departments COMMENT = 'To capture the departments.';

INSERT INTO HR.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('1', 'vinettes', 'v000/20150501_1.xml', NOW(), 1, '7:79eb8aca9ac3329f0f208bfb4aa1f71c', 'createTable', '', 'EXECUTED', '3.3.2');

--  Changeset v000/20150501_1.xml::2::vinettes
CREATE TABLE HR.employees (ID INT AUTO_INCREMENT NOT NULL, LAST_NAME CHAR(30) NOT NULL, FIRST_NAME CHAR(30) NOT NULL, DEPARTMENT_ID INT NOT NULL, SALARY DECIMAL(10, 2) NOT NULL, DOB date NOT NULL, ADDRESS VARCHAR(100) NOT NULL, STATUS_IND INT DEFAULT 1 NOT NULL, CONSTRAINT PK_EMPLOYEES PRIMARY KEY (ID));

INSERT INTO HR.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('2', 'vinettes', 'v000/20150501_1.xml', NOW(), 2, '7:0ca800db74f094e7015ba2142844b692', 'createTable', '', 'EXECUTED', '3.3.2');

--  Changeset v000/20150501_1.xml::3::vinettes
CREATE TABLE HR.territories (ID INT AUTO_INCREMENT NOT NULL, NAME VARCHAR(50) NOT NULL, CONSTRAINT PK_TERRITORIES PRIMARY KEY (ID));

INSERT INTO HR.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('3', 'vinettes', 'v000/20150501_1.xml', NOW(), 3, '7:33aa3c993b486032465907a080ea4d77', 'createTable', '', 'EXECUTED', '3.3.2');

--  Changeset v000/20150501_1.xml::4::vinettes
CREATE TABLE HR.users (ID INT AUTO_INCREMENT NOT NULL, STATUS_IND INT NOT NULL, USERNAME VARCHAR(30) NOT NULL, EMPLOYEE_ID INT NOT NULL, CONSTRAINT PK_USERS PRIMARY KEY (ID));

INSERT INTO HR.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('4', 'vinettes', 'v000/20150501_1.xml', NOW(), 4, '7:7cc9542823905172d3d71276b12d51f1', 'createTable', '', 'EXECUTED', '3.3.2');

--  Changeset v000/20150501_1.xml::5::vinettes
ALTER TABLE HR.departments ADD CONSTRAINT DEPARTMENTS_TERRITORIES_FK FOREIGN KEY (ID) REFERENCES HR.territories (TERRITORY_ID) ON UPDATE NO ACTION ON DELETE NO ACTION;

INSERT INTO HR.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('5', 'vinettes', 'v000/20150501_1.xml', NOW(), 5, '7:39f55cf39485a8d9fd73e8daf4f20e39', 'addForeignKeyConstraint', '', 'EXECUTED', '3.3.2');

--  Changeset v000/20150501_1.xml::6::vinettes
ALTER TABLE HR.employees ADD CONSTRAINT EMPLOYEES_DEPARTMENTS_FK FOREIGN KEY (ID) REFERENCES HR.departments (DEPARTMENT_ID) ON UPDATE NO ACTION ON DELETE NO ACTION;

INSERT INTO HR.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('6', 'vinettes', 'v000/20150501_1.xml', NOW(), 6, '7:6485160328e08a1b21eda154d6dbbf88', 'addForeignKeyConstraint', '', 'EXECUTED', '3.3.2');

--  Changeset v000/20150501_1.xml::7::vinettes
ALTER TABLE HR.users ADD CONSTRAINT USERS_EMPLOYEES_FK FOREIGN KEY (ID) REFERENCES HR.employees (EMPLOYEE_ID) ON UPDATE NO ACTION ON DELETE NO ACTION;

INSERT INTO HR.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('7', 'vinettes', 'v000/20150501_1.xml', NOW(), 7, '7:a8efaf039a7d9f1bb061befabea97431', 'addForeignKeyConstraint', '', 'EXECUTED', '3.3.2');

--  Release Database Lock
UPDATE HR.DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;

